FROM python:3.6-jessie

RUN apt-get update && apt-get install build-essential -y

# Unbufferend I/O for synchronous logging at dev-time
ENV PYTHONUNBUFFERED 1
RUN mkdir -p /app/panelapp

COPY .build/panelapp /app/panelapp
COPY .build/setup.py .build/setup.cfg .build/MANIFEST.in .build/VERSION /app/

WORKDIR /app

RUN pip install -e .[dev,tests]
RUN pip install django-debug-toolbar

VOLUME ["/app/panelapp"]

WORKDIR /app/panelapp

# Celery is a script and need to run in "shell mode"
ENTRYPOINT celery worker --app panelapp --task-events
CMD ["--loglevel INFO"]
