FROM python:3.6-jessie

RUN mkdir -p /app/panelapp

COPY ./panelapp /app/panelapp
COPY ./setup.py ./setup.cfg ./MANIFEST.in ./VERSION /app/

WORKDIR /app

# Install everything in editable mode, for development
RUN pip install -e .[dev,tests]
RUN pip install pytest-runner

## Prepare installation for development

# Install dev-time dependencies
RUN apt-get update && apt-get install build-essential -y

# Copy the genes file
ADD ./deploy/genes.json.tgz /app

# Unbufferend I/O for synchronous logging at dev-time
ENV PYTHONUNBUFFERED 1

# Volume to mount application sources from the host machine
VOLUME ["/app/panelapp"]

WORKDIR /app/panelapp

# Start Gunicorn web server
CMD ["gunicorn", "--workers=1", "-b :8080", "panelapp.wsgi:application"]

EXPOSE 8080
