version: '3'

services:

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4593:4567-4593"
      # Exposes LocalStack WebUI on 8090
      - "8090:8080"
    environment:
      - SERVICES=sqs,s3,ses
      - DEFAULT_REGION=${AWS_DEFAULT_REGION-eu-west-2}
      - HOSTNAME_EXTERNAL=localstack
      - DEBUG=${DEBUG- }
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
      # Make S3 bucket persistent
      - DATA_DIR=/tmp/localstack/data
#      - DATA_DIR=${DATA_DIR- }
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  db:
    image: postgres:9.6.9
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=panelapp
      - POSTGRES_DB=panelapp

  web:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile-web
    image: panelapp_web_dev
    restart: on-failure
    volumes:
      - ../../panelapp:/app/panelapp
#      - /tmp/panelapp_static:/static
#      - /tmp/panelapp_media:/media
    ports:
      - "8080:8000"
    depends_on:
      - db
#      - rabbitmq
      - localstack
    environment:
#      - DATABASE_URL=postgres://panelapp:secret@db:5432/panelapp
      - DATABASE_USER=panelapp
      - DATABASE_PASSWORD=secret
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=panelapp
      - DJANGO_SETTINGS_MODULE=panelapp.settings.docker-dev
      - DJANGO_LOG_LEVEL=DEBUG
      - HEALTH_ACCESS_TOKEN_LOCATION=/app/health_token
      - ALLOWED_HOSTS=localhost;web
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - USE_S3=TRUE
      - AWS_S3_STATICFILES_BUCKET_NAME=static-bucket
      - AWS_STATICFILES_LOCATION=static
      - AWS_S3_MEDIAFILES_BUCKET_NAME=media-bucket
      - AWS_MEDIAFILES_LOCATION=media
#      - STATIC_ROOT=/static
#      - MEDIA_ROOT=/media
      - USE_SQS=TRUE
      - CELERY_BROKER_URL=sqs://@localstack:4576
#      - CELERY_BROKER_URL=amqp://rabbitmq/panelapp

  worker:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile-worker
    image: panelapp_worker_dev
    restart: on-failure
    volumes:
      - ../../panelapp:/app/panelapp
#      - /tmp/panelapp_static:/static
#      - /tmp/panelapp_media:/media
    ports: []
    depends_on:
      - db
#      - rabbitmq
    environment:
#      - DATABASE_URL=postgres://panelapp:secret@db:5432/panelapp
      - DATABASE_USER=panelapp
      - DATABASE_PASSWORD=secret
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=panelapp
      - DJANGO_SETTINGS_MODULE=panelapp.settings.docker-dev
      - HEALTH_ACCESS_TOKEN_LOCATION=/app/health_token
      - ALLOWED_HOSTS=localhost;web
#      - MEDIA_ROOT=/media
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - USE_S3=TRUE
      - AWS_S3_MEDIAFILES_BUCKET_NAME=media-bucket
      - AWS_MEDIAFILES_LOCATION=media
      - USE_SQS=TRUE
      - CELERY_BROKER_URL=sqs://@localstack:4576
#      - CELERY_BROKER_URL=amqp://rabbitmq/panelapp

#  rabbitmq:
#    image: rabbitmq
#    environment:
#      - RABBITMQ_DEFAULT_VHOST=panelapp
