# Generated by Django 2.0.6 on 2018-06-28 15:41

from django.db import migrations
from rest_framework.authtoken.models import Token
from accounts.models import User


def generate_api_tokens(apps, schema):
    for user in User.objects.all():
        Token.objects.get_or_create(user=user)


def do_nothing(*args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180615_1147'),
    ]

    operations = [
        migrations.RunPython(generate_api_tokens, do_nothing)
    ]
