# Generated by Django 2.0.6 on 2018-07-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180724_1325'),
        ('accounts', '0008_auto_20180628_1641'),
    ]

    operations = [
    ]
