# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models
import panelapp.utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
                ('href', models.CharField(max_length=32)),
                ('text', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=panelapp.utils.storage.OverwriteStorage(), upload_to='images')),
                ('alt', models.CharField(max_length=64, verbose_name='Alterative text')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Image title')),
            ],
        ),
    ]
