# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometext',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hometext',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='hometext',
            name='href',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
