# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models
import panelapp.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('panelapp', '0003_auto_20170518_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hometext',
            options={'ordering': ['section']},
        ),
        migrations.AlterField(
            model_name='hometext',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=panelapp.utils.storage.OverwriteStorage(), upload_to='images'),
        ),
    ]
