# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import panelapp.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('panelapp', '0004_auto_20170519_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=255, storage=panelapp.utils.storage.OverwriteStorage(), upload_to='images'),
        ),
    ]
