# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedGeneList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported', models.BooleanField(default=False)),
                ('gene_list', models.FileField(upload_to='genes')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedPanelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_list', models.FileField(upload_to='panels')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedReviewsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.FileField(upload_to='reviews')),
            ],
        ),
    ]
