# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 13:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_symbol', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gene_name', models.CharField(max_length=255)),
                ('other_transcripts', django.contrib.postgres.fields.jsonb.JSONField()),
                ('omim_gene', models.CharField(max_length=255)),
            ],
        ),
    ]
