# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0003_auto_20170526_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genepanelsnapshot',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
    ]
