# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170530_1414'),
        ('panels', '0004_auto_20170526_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genepanelentrysnapshot',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='genepanelsnapshot',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-major_version', '-minor_version']},
        ),
        migrations.AlterModelOptions(
            name='trackrecord',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='source_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='type',
        ),
        migrations.AddField(
            model_name='evidence',
            name='legacy_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Reviewer'),
        ),
        migrations.AddField(
            model_name='genepanelentrysnapshot',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='genepanelentrysnapshot',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='genepanelentrysnapshot',
            name='saved_gel_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trackrecord',
            name='curator_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackrecord',
            name='gel_status',
            field=models.IntegerField(default=0),
        ),
    ]
