# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 15:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0009_auto_20170613_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genepanelentrysnapshot',
            name='contributors',
        ),
        migrations.AlterField(
            model_name='genepanelsnapshot',
            name='old_panels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None),
        ),
    ]
