# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0010_auto_20170613_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='genepanel',
            name='old_pk',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
