# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0012_auto_20170614_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpanellist',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedreviewslist',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
