# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0015_auto_20170616_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedgenelist',
            name='gene_list',
            field=models.FileField(max_length=255, upload_to='genes'),
        ),
        migrations.AlterField(
            model_name='uploadedpanellist',
            name='panel_list',
            field=models.FileField(max_length=255, upload_to='panels'),
        ),
        migrations.AlterField(
            model_name='uploadedreviewslist',
            name='reviews',
            field=models.FileField(max_length=255, upload_to='reviews'),
        ),
    ]
