# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 11:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0017_auto_20170621_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genepanelentrysnapshot',
            name='phenotypes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), blank=True, null=True, size=None),
        ),
    ]
