# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0023_auto_20170724_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
