# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 08:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0024_gene_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genepanelentrysnapshot',
            name='gene',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
