# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0027_auto_20170823_1210'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='genepanelentrysnapshot',
            index=models.Index(fields=['gene_core_id'], name='panels_gene_gene_co_9223b2_idx'),
        ),
    ]
