# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0028_auto_20170824_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='genepanel',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
