# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0031_auto_20171107_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpanellist',
            name='import_log',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='uploadedreviewslist',
            name='import_log',
            field=models.TextField(default=''),
        ),
    ]
