# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0031_auto_20171107_1003'),
        ('panels', '0030_auto_20171101_1312'),
    ]

    operations = [
    ]
