# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0031_auto_20171107_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='genepanel',
            name='status',
            field=models.CharField(choices=[('promoted', 'promoted'), ('public', 'public'), ('retired', 'retired'), ('internal', 'internal'), ('deleted', 'deleted')], default='internal', max_length=36),
        ),
    ]
