# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0032_merge_20171107_1651'),
        ('panels', '0032_auto_20171130_1702'),
    ]

    operations = [
    ]
