# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0032_auto_20171130_1702'),
        ('panels', '0034_auto_20171207_1139'),
    ]

    operations = [
    ]
