# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0043_evaluation_clinically_relevant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='clinically_relevant',
            field=models.NullBooleanField(default=False, help_text='Interruptions in the normal alleles are reported as part of standard diagnostic practice'),
        ),
    ]
