# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-14 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0047_auto_20180509_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gene',
            options={},
        ),
    ]
