# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0048_auto_20180606_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='gene_symbol',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='str_name',
        ),
    ]
