# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0049_auto_20180607_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='text',
            field=models.TextField(),
        ),
    ]
