# Generated by Django 2.0.6 on 2018-06-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0052_auto_20180615_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='genepanelsnapshot',
            name='child_panels',
            field=models.ManyToManyField(to='panels.GenePanelSnapshot'),
        ),
    ]
