# Generated by Django 2.1.3 on 2019-04-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0070_auto_20190402_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
