# Generated by Django 2.1.3 on 2019-05-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0071_auto_20190424_1526'),
        ('panels', '0071_comment_version'),
    ]

    operations = [
    ]
