# FIXME fully qualify the base image, including a tag
FROM panelapp-base

WORKDIR /app/panelapp
ENTRYPOINT celery worker --app panelapp --task-events
CMD ["--loglevel INFO"]
# FIXME Configure  number of celery threads
