FROM python:3.6-8-alpine3.9

# Better to buffer stdout logging, for performance
ENV PYTHONUNBUFFERED 0

RUN mkdir -p /app/panelapp

COPY ./panelapp /app/panelapp
COPY ./setup.py ./setup.cfg ./MANIFEST.in ./VERSION /app/

WORKDIR /app

RUN pip install .


WORKDIR /app/panelapp
EXPOSE 8080
CMD ["gunicorn", "--workers=2", "-b :8000", "panelapp.wsgi:application"]
