# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:34
from __future__ import unicode_literals

import backups.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanelBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=256)),
                ('old_panels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('old_pk', models.CharField(max_length=32, null=True)),
                ('original_pk', models.IntegerField()),
                ('major_version', models.IntegerField()),
                ('minor_version', models.IntegerField()),
                ('number_of_genes', models.IntegerField()),
                ('gene_symbols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('genes_content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TSVBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tsv', models.FileField(upload_to=backups.models.panel_version_path)),
                ('panel_backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.PanelBackup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
