from .panels import AdminView
from .panels import AdminUploadGenesView
from .panels import AdminUploadPanelsView
from .panels import AdminUploadReviewsView
from .panels import DownloadAllPanels
from .panels import ActivityListView
from .panels import CreatePanelView
from .panels import GenePanelView
from .panels import PanelsIndexView
from .panels import UpdatePanelView
from .panels import PromotePanelView
from .genes import GeneDetailView
from .genes import GeneListView
from .genes import PanelAddGeneView
from .genes import PanelEditGeneView
from .genes import GeneReviewView
from .genes import DownloadPanelTSVView
from .genes import DownloadPanelVersionTSVView
from .genes import ComparePanelsView
from .genes import CompareGeneView
from .genes import CopyReviewsView
from .genes import DownloadAllGenes
from .entities import PanelMarkNotReadyView
from .entities import GenePanelSpanshotView
from .entities import MarkGeneReadyView
from .entities import MarkGeneNotReadyView
from .strs import PanelAddSTRView
